### ISSUE TITLE
可以修改手机型号吗?

### ISSUE THREAD

**Issue by Kyrie-leon** [solywsh/wozaixiaoyuancheck#2]
学校不允许用PC端登录,而且换手机会被发现

**Comment by solywsh** [comment]
可以的，电脑和手机处于同一个局域网可以用charles进行抓包，具体的可以百度

发自我的iPhone

在 2021年2月7日，11:19，leon <notifications@github.com> 写道：

﻿

Reopened #2<https://github.com/solywsh/wozaixiaoyuancheck/issues/2>.

**Comment by solywsh** [comment]
在每个函数的`header`中，找到`user-agent`，把后面的内容换成`Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.2(0x18000229) NetType/WIFI Language/zh_CN`，即可

**Comment by Kyrie-leon** [comment]
好的,我试一试

**Comment by solywsh** [comment]
可以，需要自行抓包

发自我的iPhone

在 2021年2月23日，17:38，leon <notifications@github.com> 写道：

﻿

Closed #2<https://github.com/solywsh/wozaixiaoyuancheck/issues/2>.
